@include('layouts.footer')
@include('layouts.rightNav')
@include('layouts.nav')
@include('layouts.signin')
@include('layouts.signup')
@include('layouts.reset')
@include('layouts.options')
@include('layouts.optionsOffre')